[amsclient]
url = ""
client_id = ""
client_secret = ""
page_size = 100

[server]
address = ":8081"
api_dbg_prefix = "/api/dbg/"
api_v1_prefix = "/api/v1/"
api_v2_prefix = "/api/v2/"
api_v1_spec_file = "server/api/v1/openapi.json"
api_v2_spec_file = "server/api/v2/openapi.json"
debug = true
auth = true
auth_type = "jwt"
use_https = false
enable_cors = true
enable_internal_rules_organizations = false
internal_rules_organizations = []
log_auth_token = true
org_clusters_fallback = true

[services]
aggregator = "http://localhost:8080/api/insights-results-aggregator/v1/"
content = "http://localhost:8082/api/v1/"
groups_poll_time = "60s"
content_directory_timeout = "1s"

[setup]
internal_rules_organizations_csv_file = ""

[metrics]
namespace = "smart_proxy"

[redis]
database = 0
endpoint = "localhost:6379"
password = ""
timeout_seconds = 30
