---
apiVersion: v1
kind: Template
metadata:
  name: ccx-smart-proxy
objects:

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    labels:
      app: ccx-smart-proxy
    name: ccx-smart-proxy
  spec:
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    scaleTargetRef:
      apiVersion: v1
      kind: Deployment
      name: ccx-smart-proxy
    targetCPUUtilizationPercentage: 80

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ccx-smart-proxy
  spec:
    envName: ${ENV_NAME}
    dependencies:
      - ingress
    deployments:
      - name: smart-proxy
        minReplicas: ${{MIN_REPLICAS}}
        webServices:
          public:
            enabled: false
          private:
            enabled: false
          metrics:
            enabled: true
        podSpec:
          env:
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__ADDRESS
              value: ":8080"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__API_PREFIX
              value: "${IRSP_API_PREFIX}"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__API_SPEC_FILE
              value: "/openapi/openapi.json"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__DEBUG
              value: "${DEBUG}"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__AUTH
              value: "${AUTH}"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__AUTH_TYPE
              value: "xrh"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVER__ENABLE_INTERNAL_RULES_ORGANIZATIONS
              value: "${IRSP_ENABLE_INTERNAL_ORGANIZATIONS}"
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVICES__AGGREGATOR
              value: ${INSIGHTS_RESULTS_AGGREGATOR_SERVICE_URL}
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVICES__CONTENT
              value: ${INSIGHTS_CONTENT_SERVICE_URL}
            - name: INSIGHTS_RESULTS_SMART_PROXY__SERVICES__GROUPS_POLL_TIME
              value: ${INSIGHTS_CONTENT_SERVICE_POLL_TIME}
            - name: INSIGHTS_RESULTS_SMART_PROXY__SETUP__INTERNAL_RULES_ORGANIZATIONS_CSV_FILE
              value: /etc/ccx-smart-proxy-secrets/internal_rules_organizations.csv
            - name: INSIGHTS_RESULTS_SMART_PROXY__LOGGING__LOGGING_TO_CLOUD_WATCH_ENABLED
              value: ${LOGGING_TO_CLOUD_WATCH_ENABLED}
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__DEBUG
              value: ${CLOUDWATCH_DEBUG}
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__STREAM_NAME
              value: ${IRSP_LOG_STREAM}
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__CREATE_STREAM_IF_NOT_EXISTS
              value: ${CREATE_STREAM_IF_NOT_EXISTS}
            - name: HABERDASHER_EMITTER
              value: ${HABERDASHER_EMITTER}
            - name: HABERDASHER_KAFKA_BOOTSTRAP
              value: ${HABERDASHER_KAFKA_BOOTSTRAP}
            - name: HABERDASHER_KAFKA_TOPIC
              value: ${HABERDASHER_KAFKA_TOPIC}
            - name: HABERDASHER_LABELS
              value: ${HABERDASHER_LABELS}
            - name: HABERDASHER_TAGS
              value: ${HABERDASHER_TAGS}
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__LOG_GROUP
              valueFrom:
                secretKeyRef:
                  key: log_group_name
                  name: cloudwatch
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: cloudwatch
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__AWS_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: cloudwatch
            - name: INSIGHTS_RESULTS_SMART_PROXY__CLOUDWATCH__AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: cloudwatch
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 250m
              memory: 600Mi
parameters:
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/ccx-smart-proxy
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  required: true
- description: Minimum number of pods to use when autoscaling is enabled
  name: MIN_REPLICAS
  value: '2'
- description: Minimum number of pods to use when autoscaling is enabled
  name: MAX_REPLICAS
  value: '16'
- name: PAYLOAD_TRACKER_TOPIC
  description: Kafka topic for publishing updated for the Payload Tracker service
  value: platform.payload-status
- name: HABERDASHER_EMITTER
  description: Emitter for haberdasher logs [stderr|kafka]
  value: stderr
- name: HABERDASHER_KAFKA_BOOTSTRAP
  description: Bootstrap server for haberdasher kafka emitter
  value: "mq-kafka:29092"
- name: HABERDASHER_KAFKA_TOPIC
  description: Kafka topic for haberdasher kafka emitter
  value: "platform.logging.logs"
- name: DEBUG
  value: "true"
- name: AUTH
  value: "false"
